export const UNIVERSITIES = [
  'MIT', 'Stanford University', 'Harvard University', 'Caltech', 'Carnegie Mellon University',
  'UC Berkeley', 'UCLA', 'UC San Diego', 'UC Davis', 'UC Santa Barbara',
  'University of Michigan', 'University of Illinois Urbana-Champaign', 'Georgia Tech',
  'Cornell University', 'Princeton University', 'Yale University', 'Columbia University',
  'University of Washington', 'University of Texas at Austin', 'Purdue University',
  'Penn State University', 'Ohio State University', 'University of Wisconsin-Madison',
  'University of Minnesota', 'University of Florida', 'University of Southern California',
  'New York University', 'Boston University', 'Northeastern University', 'Tufts University',
  'Brown University', 'Dartmouth College', 'Duke University', 'Vanderbilt University',
  'Rice University', 'University of Notre Dame', 'Georgetown University', 'Emory University',
  'University of Virginia', 'University of North Carolina', 'University of Maryland',
  'Rutgers University', 'University of Pittsburgh', 'Case Western Reserve University',
  'Rensselaer Polytechnic Institute', 'Worcester Polytechnic Institute', 'Stevens Institute of Technology',
  'UMass Amherst', 'UMass Boston', 'University of Connecticut', 'University of Rochester',
  'Syracuse University', 'Lehigh University', 'Drexel University', 'Temple University',
  'University of Delaware', 'University of Colorado Boulder', 'University of Arizona',
  'Arizona State University', 'University of Utah', 'University of Oregon',
  'Oregon State University', 'University of Iowa', 'Iowa State University',
  'University of Kansas', 'University of Missouri', 'Indiana University', 'Purdue University',
  'Michigan State University', 'University of Cincinnati', 'Ohio University', 'Miami University',
  'University of Alabama', 'Auburn University', 'University of Georgia', 'Clemson University',
  'Virginia Tech', 'William & Mary', 'University of Tennessee', 'University of Kentucky',
  'Louisiana State University', 'Tulane University', 'Texas A&M University', 'UT Dallas',
]
