// Maps canonical stored EEO values → known ATS phrasings (case-insensitive match applied at runtime)
export const EEO_ALIASES: Record<string, string[]> = {
  'Decline to self-identify': [
    "decline to self-identify",
    "i don't wish to answer",
    "i prefer not to say",
    "prefer not to say",
    "prefer not to disclose",
    "choose not to disclose",
    "i do not wish to provide this information",
    "i do not wish to identify",
    "decline to identify",
    "i choose not to answer",
    "not disclosed",
    "undisclosed",
  ],
  'Male': ['male', 'man', 'he/him'],
  'Female': ['female', 'woman', 'she/her'],
  'Non-binary': ['non-binary', 'nonbinary', 'they/them', 'gender non-conforming', 'genderqueer'],
  'Not a veteran': [
    'not a veteran',
    'i am not a protected veteran',
    'i am not a veteran',
    'no',
  ],
  'Protected veteran': [
    'protected veteran',
    'i am a protected veteran',
    'i identify as a protected veteran',
    'yes',
  ],
  'Yes': ['yes', 'i have a disability', 'i have a disability or condition'],
  'No': ['no', 'i do not have a disability', "i don't have a disability"],
  'American Indian or Alaskan Native': ['american indian or alaskan native', 'american indian or alaska native', 'native american'],
  'Asian': ['asian', 'asian american'],
  'Black or African American': ['black or african american', 'black', 'african american'],
  'Hispanic or Latino': ['hispanic or latino', 'hispanic', 'latino', 'latina', 'latinx'],
  'Native Hawaiian or Other Pacific Islander': ['native hawaiian or other pacific islander', 'pacific islander'],
  'Two or more races': ['two or more races', 'multiracial', 'two or more', 'mixed race'],
  'White': ['white', 'caucasian', 'white (not of hispanic or latino origin)'],
}
