// Maps canonical stored EEO values → known ATS phrasings (case-insensitive match applied at runtime)
export const EEO_ALIASES: Record<string, string[]> = {
  'Decline to self-identify': [
    "decline to self-identify",
    "i don't wish to answer",
    "i do not wish to answer",
    "i prefer not to say",
    "prefer not to say",
    "prefer not to disclose",
    "choose not to disclose",
    "i do not wish to provide this information",
    "i do not wish to identify",
    "decline to identify",
    "i choose not to answer",
    "not disclosed",
    "undisclosed",
  ],
  'Prefer not to say': [
    "prefer not to say",
    "prefer not to disclose",
    "i prefer not to say",
    "i'd prefer not to say",
    "i don't wish to answer",
    "i do not wish to answer",
    "choose not to disclose",
    "decline to self-identify",
    "decline to identify",
  ],
  'Male': ['male', 'man', 'he/him', 'he / him'],
  'Female': ['female', 'woman', 'she/her', 'she / her'],
  'Non-binary': ['non-binary', 'nonbinary', 'they/them', 'they / them', 'gender non-conforming', 'genderqueer'],
  'Not a veteran': [
    'not a veteran',
    'i am not a protected veteran',
    'i am not a veteran',
    'i identify as not a protected veteran',
  ],
  'Protected veteran': [
    'protected veteran',
    'i am a protected veteran',
    'i identify as a protected veteran',
    'i am a disabled veteran',
    'disabled veteran',
    'active duty wartime or campaign badge veteran',
    'armed forces service medal veteran',
  ],
  'Yes': [
    'yes',
    'i have a disability',
    'i have a disability or condition',
    'yes, i have a disability',
    'yes, i have a disability, or have had one in the past',
    'i have a disability, or have had one in the past',
    'i have a disability or have had one in the past',
  ],
  'No': [
    'no',
    'i do not have a disability',
    "i don't have a disability",
    'no, i do not have a disability',
    'no, i do not have a disability and have not had one in the past',
    'i do not have a disability and have not had one in the past',
  ],
  'American Indian or Alaskan Native': [
    'american indian or alaskan native',
    'american indian or alaska native',
    'native american',
    'indigenous american',
  ],
  'Asian': ['asian', 'asian american', 'south asian', 'east asian', 'southeast asian'],
  'Black or African American': ['black or african american', 'black', 'african american'],
  'Hispanic or Latino': ['hispanic or latino', 'hispanic', 'latino', 'latina', 'latinx', 'latin american'],
  'Native Hawaiian or Other Pacific Islander': [
    'native hawaiian or other pacific islander',
    'pacific islander',
    'native hawaiian',
  ],
  'Two or more races': ['two or more races', 'multiracial', 'two or more', 'mixed race', 'biracial'],
  'White': ['white', 'caucasian', 'white (not of hispanic or latino origin)', 'white/caucasian'],
}
